all:
  children:
    debian:
      hosts:
        debian01:
          ansible_host: ubnt-lab.homelab.com
      vars:
        ansible_user: rafaria
    rocky:
      hosts:
        rocky01:
          ansible_host: rocky-lab.homelab.com
    servidores-linux:
      children:
        debian: {}
        rocky: {}
    windows:
      hosts:
        win-lab.homelab.com:
    servidores:
      hosts:
        netbox.homelab.com:
    sw1:
      hosts:
        192.168.110.1:
        192.168.110.2:
    sw2:
      hosts:
        192.168.110.254:
    switches:
      children:
        sw1: {}
        sw2: {}
      vars:
        ansible_user: admin
        ansible_password: cisco
        ansible_connection: network_cli
        ansible_network_os: ios
    tudo:
      children:
        switches: {}
        servidores: {}
        servidores-linux: {}
    devnet:
      hosts:
        devnetsandboxiosxec8k.cisco.com:
      vars:
        ansible_user: rafael.rafaria
        ansible_password: Z64g_qeUAE-Mt8
        ansible_connection: network_cli
        ansible_network_os: ios
